version: '3.1'
services:
  web:
    build: .
    depends_on:
      - mongo
    ports:
     - "3000:3000"
    networks:
      - piedpiper
    environment:
      - mongo_host="mongo"
  mongo:
    image: "mongo:3.6"
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/mongo/db
    networks:
      - piedpiper
  apicron:
    image: "stevenweathers/movie-upc-api-cronjob"
    depends_on:
      - mongo
    networks:
      - piedpiper
    environment:
      - mongo_host="mongo"
      - mongo_db="movieupc"
      - mongo_collection="movies"

networks:
  piedpiper:
    driver: bridge

volumes:
  dbdata:
